import { useState, useRef, useEffect } from "react";
import { Send, Sparkles, Bot, User } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

export default function AiChat({ patients, guides }) {
  const [messages, setMessages] = useState([{ role: "assistant", content: "Hola, soy tu asistente clínico de enfermería. Puedo ayudarte a explicar diagnósticos NANDA, recomendar intervenciones NIC, justificar evidencia o evaluar riesgos. ¿En qué necesitas apoyo?" }]); const [input, setInput] = useState(""); const [loading, setLoading] = useState(false); const [patientId, setPatientId] = useState(""); const endRef = useRef(null);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, loading]);
  async function send() { if (!input.trim() || loading) return; const userMsg = input; setMessages(m => [...m, { role: "user", content: userMsg }]); setInput(""); setLoading(true); try { const patient = patients.find(p => p.id === patientId); const context = guides.slice(0, 5).map(g => `${g.title}: ${g.content}`).join("\n"); const result = await base44.integrations.Core.InvokeLLM({ prompt: `Eres un asistente clínico de enfermería. Responde en español, de forma clara y profesional, basándote en taxonomías NANDA-I, NOC y NIC. ${patient ? `Contexto del paciente: ${JSON.stringify(patient)}.` : ""} ${context ? `Guías disponibles: ${context}.` : ""} Pregunta del profesional: ${userMsg}. Recuerda siempre que el juicio clínico corresponde al profesional.`, add_context_from_internet: true, model: "gemini_3_flash" }); setMessages(m => [...m, { role: "assistant", content: typeof result === "string" ? result : JSON.stringify(result) }]); } catch { setMessages(m => [...m, { role: "assistant", content: "No pude procesar la consulta en este momento. Inténtalo de nuevo." }]); } finally { setLoading(false); } }
  return <section className="flex h-[calc(100vh-220px)] flex-col rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 p-4"><Sparkles className="h-5 w-5 text-violet-700" /><div><h2 className="font-bold text-slate-900">Asistente IA clínico</h2><p className="text-xs text-slate-500">Consulta con contexto del paciente y guías</p></div><select className="ml-auto h-9 rounded-md border bg-white px-3 text-sm" value={patientId} onChange={e => setPatientId(e.target.value)}><option value="">Sin paciente seleccionado</option>{patients.map(p => <option key={p.id} value={p.id}>{p.full_name}</option>)}</select></div><div className="flex-1 space-y-4 overflow-y-auto p-4">{messages.map((msg, i) => <div key={i} className={`flex gap-3 ${msg.role === "user" ? "justify-end" : ""}`}>{msg.role === "assistant" && <div className="mt-1 rounded-lg bg-violet-100 p-2 text-violet-700"><Bot className="h-4 w-4" /></div>}<div className={`max-w-[75%] rounded-2xl px-4 py-2.5 text-sm ${msg.role === "user" ? "bg-teal-700 text-white" : "bg-slate-100 text-slate-800"}`}>{msg.content}</div>{msg.role === "user" && <div className="mt-1 rounded-lg bg-teal-100 p-2 text-teal-700"><User className="h-4 w-4" /></div>}</div>)}{loading && <div className="flex gap-3"><div className="mt-1 rounded-lg bg-violet-100 p-2 text-violet-700"><Bot className="h-4 w-4" /></div><div className="rounded-2xl bg-slate-100 px-4 py-2.5 text-sm text-slate-400"><span className="animate-pulse">Analizando…</span></div></div>}<div ref={endRef} /></div><div className="border-t border-slate-100 p-4"><div className="flex gap-2"><Textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Escribe tu consulta clínica…" className="min-h-10 max-h-32" /><Button onClick={send} disabled={loading || !input.trim()} className="bg-violet-700 hover:bg-violet-800"><Send className="h-4 w-4" /></Button></div></div></section>;
}